import { SVGProps, SyntheticEvent } from 'react'

export type Size =
  | 'xxxs'
  | 'xxs'
  | 'xs'
  | 'sm'
  | 'md'
  | 'lg'
  | 'xl'
  | 'xxl'
  | 'xxxl'

type nonCapitalisedString = `${
  | 'a'
  | 'b'
  | 'c'
  | 'd'
  | 'e'
  | 'f'
  | 'g'
  | 'h'
  | 'i'
  | 'j'
  | 'k'
  | 'l'
  | 'm'
  | 'n'
  | 'o'
  | 'p'
  | 'q'
  | 'r'
  | 's'
  | 't'
  | 'u'
  | 'v'
  | 'w'
  | 'x'
  | 'y'
  | 'z'}${string}`

export type Color =
  | 'Blue500'
  | 'Blue200'
  | 'WhiteWhite100'
  | 'GreyscaleGrey100'
  | 'TextPrimary'
  | 'TextSecondary'
  | 'TextDisabled'
  | 'TextInverted'
  | 'PrimaryMain'
  | 'PrimaryMainHover'
  | 'PrimaryMainSelected'
  | 'PrimaryMainContrast'
  | 'PrimaryMainContrastSecondary'
  | 'PrimaryLight'
  | 'PrimaryLightHover'
  | 'PrimaryLightSelected'
  | 'PrimaryLightContrast'
  | 'PrimaryLightContrastSecondary'
  | 'PrimaryMainOutline'
  | 'PrimaryLightOutline'
  | 'ActionMain'
  | 'ActionMainHover'
  | 'ActionMainSelected'
  | 'ActionMainContrast'
  | 'ActionMainContrastSecondary'
  | 'ActionLight'
  | 'ActionLightHover'
  | 'ActionLightSelected'
  | 'ActionLightContrast'
  | 'ActionLightContrastSecondary'
  | 'ActionMainOutline'
  | 'ActionLightOutline'
  | 'OtherDisabledContent'
  | 'OtherDisabledBackground'
  | 'OtherDisabledOutline'
  | 'OtherForeground'
  | 'OtherForegroundInverted'
  | 'OtherDivider'
  | 'OtherOverlay'
  | 'OtherInputBorderDefault'
  | 'OtherInputBorderHover'
  | 'OtherInputBorderActive'
  | 'ErrorMain'
  | 'ErrorMainHover'
  | 'ErrorMainSelected'
  | 'ErrorMainContrast'
  | 'ErrorMainContrastSecondary'
  | 'ErrorLight'
  | 'ErrorLightHover'
  | 'ErrorLightSelected'
  | 'ErrorLightContrast'
  | 'ErrorLightContrastSecondary'
  | 'ErrorMainOutline'
  | 'ErrorLightOutline'
  | 'Background0dp'
  | 'Background1dp'
  | 'Background2dp'
  | 'Background3dp'
  | 'CalloutMain'
  | 'AccentRed'
  | 'AccentRedLight'
  | 'AccentOrange'
  | 'AccentOrangeLight'
  | 'AccentYellow'
  | 'AccentYellowLight'
  | 'AccentMustard'
  | 'AccentMustardLight'
  | 'AccentForestgreen'
  | 'AccentForestgreenLight'
  | 'AccentGreen'
  | 'AccentGreenLight'
  | 'AccentTeal'
  | 'AccentTealLight'
  | 'AccentBabyblue'
  | 'AccentBabyblueLight'
  | 'AccentSailorblue'
  | 'AccentSailorblueLight'
  | 'AccentDarkpurple'
  | 'AccentDarkpurpleLight'
  | 'AccentPurple'
  | 'AccentPurpleLight'
  | 'AccentBrightpurple'
  | 'AccentBrightpurpleLight'
  | 'AccentPink'
  | 'AccentPinkLight'
  | (nonCapitalisedString & {})

export type Icon = SVGProps<SVGSVGElement> & {
  color?: Color
  size?: number
}

export type PropsEventHandler<E = SyntheticEvent, P = any> = (
  e?: E,
  props?: P
) => void | Promise<void> | boolean | Promise<boolean>
