export * from './color'
export * from './border'
export * from './boxShadow'
export * from './font'
export * from './hrefIsActive'
export * from './numberString'
export * from './toRGBA'
export * from './renderOrCreateElement'
export * from './stringToIcon'
export * from './spaceToPx'
export * from './setLocation'
export * from './copyToClipboard'
export * from './generatePlural'
export * from './isTouchDevice'
export * from './isPhone'
export * from './isMac'
// TODO: export all util files in the same way
